//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaterialDbEntities : DbContext
    {
        public MaterialDbEntities()
            : base("name=MaterialDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbActivity> tbActivities { get; set; }
        public virtual DbSet<tbCity> tbCities { get; set; }
        public virtual DbSet<tbClassification> tbClassifications { get; set; }
        public virtual DbSet<tbContextVolunteerSupported> tbContextVolunteerSupporteds { get; set; }
        public virtual DbSet<tbDetail> tbDetails { get; set; }
        public virtual DbSet<tbSupportedInfo> tbSupportedInfoes { get; set; }
        public virtual DbSet<tbTip> tbTips { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
        public virtual DbSet<tbVolunteerInfo> tbVolunteerInfoes { get; set; }
    }
}
