//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContextVolunteerSupported
    {
        public int Id { get; set; }
        public int Volunteer_Id { get; set; }
        public int Supported_Id { get; set; }
    
        public virtual tbSupportedInfo tbSupportedInfo { get; set; }
        public virtual tbVolunteerInfo tbVolunteerInfo { get; set; }
    }
}
