//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDetail()
        {
            this.tbUsers = new HashSet<tbUser>();
        }
    
        public int Id { get; set; }
        public string strAddress { get; set; }
        public int City_Id { get; set; }
        public string strPhone { get; set; }
    
        public virtual tbCity tbCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers { get; set; }
    }
}
