//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbSupportedInfoes = new HashSet<tbSupportedInfo>();
            this.tbVolunteerInfoes = new HashSet<tbVolunteerInfo>();
        }
    
        public int Id { get; set; }
        public string strFirstName { get; set; }
        public string strLastName { get; set; }
        public string strEmail { get; set; }
        public string strPassword { get; set; }
        public int Classification_Id { get; set; }
        public int Details_Id { get; set; }
        public int Age { get; set; }
        public System.DateTime Date_Registration { get; set; }
        public string strTZ { get; set; }
        public bool Mode { get; set; }
    
        public virtual tbClassification tbClassification { get; set; }
        public virtual tbDetail tbDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSupportedInfo> tbSupportedInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVolunteerInfo> tbVolunteerInfoes { get; set; }
    }
}
